#!/usr/bin/env python3
"""
Pre-build static site generator - run this locally before deploying
"""

import os
import json
import shutil
from pathlib import Path

def create_static_site():
    """Create a completely static version of the site"""
    
    # Create dist directory
    dist_dir = Path('dist')
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
    dist_dir.mkdir()
    
    # Copy static assets
    static_src = Path('service_call_analyzer/static')
    if static_src.exists():
        # Copy CSS, JS, and other static files
        for item in static_src.iterdir():
            if item.is_file():
                shutil.copy2(item, dist_dir)
            elif item.is_dir():
                shutil.copytree(item, dist_dir / item.name, dirs_exist_ok=True)
    
    # Load data with explicit UTF-8 encoding
    with open('service_call_analyzer/media/call.json', 'r', encoding='utf-8') as f:
        call_data = json.load(f)
    
    with open('service_call_analyzer/static/custom_analysis.json', 'r', encoding='utf-8') as f:
        custom_analysis = json.load(f)
    
    # Create a simple HTML file with embedded data
    html_content = create_html_with_data(call_data, custom_analysis)
    
    # Write index.html
    with open(dist_dir / 'index.html', 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print("✅ Static site generated in 'dist' directory")
    print("📁 Ready for deployment to Vercel!")

def create_html_with_data(call_data, custom_analysis):
    """Create HTML with embedded JSON data"""
    
    # Process the data
    stages = []
    for check in call_data.get('compliance_check', []):
        stage = check.get('stage')
        if stage and stage not in stages:
            stages.append(stage)
    
    # Create the HTML
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service Call Analysis</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">
</head>
<body>
    <!-- Navigation Header -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <i class="bi bi-telephone-fill me-2"></i>
                Service Call Analyzer
            </a>
        </div>
    </nav>

    <!-- Main Content -->
    <main class="main-content">
        <div id="app">
            <!-- Content will be generated by JavaScript -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 text-center py-5">
                        <div class="spinner-border text-primary" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <p class="mt-3">Loading call analysis...</p>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!-- Embedded Data -->
    <script>
        window.CALL_DATA = {json.dumps(call_data, indent=2)};
        window.CUSTOM_ANALYSIS = {json.dumps(custom_analysis, indent=2)};
    </script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- Custom JS -->
    <script src="/js/main.js"></script>
    <script src="/js/app.js"></script>
</body>
</html>"""

if __name__ == '__main__':
    create_static_site()